### ISSUE TITLE
toString parsing error on day of week step

### ISSUE THREAD

**Issue by Vija02** [roccivic/cron-converter#10]
Error when parsing array specifically on day of week, step expression

Parse [1, 3, 5]
Result when toString() should be 1/2 or just plain 1,3,5

Instead, the result is */2, which is effectively [0, 2, 4, 6].
Not sure if problem with parsing or when displaying to string.

Might also be the same for hours and minutes

Edit: Looks like the problem lies when converting to string

**Comment by roccivic** [comment]
Thanks for reporting and providing a PR, indeed the behavior was incorrect.
