### ISSUE TITLE
validate function to validate the next date

### ISSUE THREAD

**Issue by bennigames** [roccivic/cron-converter#18]
for me it would help if there was a possible "validate" method as an option so one can validate the "next" date and if the method returns `false` the seeker finds the next day until the validator returns `true` or an iteration count of x was reached (to prevent endless loops)

**Comment by roccivic** [comment]
I'm not against this, but it looks like only about 10 lines of code to wrap the `next`/`prev` methods.
Are you sure you don't want to implement this on your end?

```js
const next = (schedule, reference, validate, limit) => {
    let date = schedule.next(reference)
    while (limit--) {
        if (validate(date)) {
            return date;
        }
        date = schedule.next(date);
    }
    throw new Error('Retry limit exceeded while looking for next schedule execution time')
}
```
