### ISSUE TITLE
timezone support

### ISSUE THREAD

**Issue by rstacruz** [roccivic/cron-converter#2]
it would be nice to use moment-timezone.

**Comment by roccivic** [comment]
I'm not sure I understand what you mean. Could you please elaborate.

**Comment by rstacruz** [comment]
For instance, I can do this to figure out when the next will be:

```js
cron = new CronTime('0 12 * * *')
cron.next()  // => "Jan 22, 12:00:00PM +08:00 GMT"
```

However, this assumes that the timezone is my own system time's... that is, 12:00 noon Singapore time. When it's time to deploy my app to, say, a remote server in California... it won't work as I expect it anymore.

I worked around this using:

```js 
cron = new CronTime('0 12 * * *')
now = moment().tz('America/Los_Angeles')
cron.next(now)
```

(...on second thought, actually, maybe this workaround is already sufficient?)

**Comment by rstacruz** [comment]
On second thought, maybe this workaround is already sufficient? If so, then it might be worth documenting it.

**Comment by roccivic** [comment]
Yeah, this seems like a reasonable workaround. And it avoids adding a dependency of ```moment-timezone```.
I've added a few lines about this to README.md in 4cf7042a8527701c9a443a07cbce3c33cc98ffd4

Thank you.

**Comment by roccivic** [comment]
This needs to be looked at again.
