### ISSUE TITLE
scheduler.next for 1 1 1 1 1 is returning value which is first day of first month and matching the exact weekday

### ISSUE THREAD

**Issue by viswassaripalli** [roccivic/cron-converter#29]
CRON: '1 1 1 1 1'
schedule.next() returns 2029-01-01 because its monday on 01-01-2029
but its should return 2025-01-01 // Today: 2024-12-02
![Screenshot 2024-12-02 at 3 20 05 PM](https://github.com/user-attachments/assets/8594c091-c32a-4064-bf30-937ebc7063e6)

**Comment by roccivic** [comment]
Hi @viswassaripalli, thank you for your contribution.

I am not sure I understand the issue. You stated that the reference date, `today`, is `2024-12-02` and that you want the next execution for `1 1 1 1 1`. For this case the correct result is `2029-01-01` as `2024-01-01` is already in the past relative to the reference date. If you want the result to be `2024-01-01`, you need to set the reference date further into the past, perhaps `2023-12-02` or look for the previous execution time, not next.

In the screenshot below, you can see the expected execution times relative to today, 8th of December 2024, which look correct to me (https://cron-converter-demo.netlify.app/).

I am going to close the issue as I don't think there anything actionable here for me. If you still think that there is a bug in the library, please re-open the issue and add a code snippet that can be used to reproduce the bug.

Thank you.

<img width="1280" alt="Screenshot 2024-12-08 at 10 08 07 AM" src="https://github.com/user-attachments/assets/014cf314-8b4a-476d-b311-a3b2b33cdab7">

**Comment by viswassaripalli** [comment]
Sorry for the typo. Its should be 2025-01-01. As shown in the above screenshot attached

**Comment by roccivic** [comment]
No worries.

2025-01-01 is a Wednesday and is therefore not the correct next execution time for `1 1 1 1 1`. If you don't want to match the exact weekday, then the correct expression to use is `1 1 1 1 *`. In this case the weekday constraint will be ignored and the result will be any 1st of January.

The screenshot that you posted looks very inaccurate to me as it also contains next execution times in their list that don't even correctly match the day of the month.

I imagine what you are seeing is a bug in the "crontab guru" application and should be reported to the maintainer of that project.

<img width="1043" alt="Screenshot 2024-12-08 at 10 23 29 AM" src="https://github.com/user-attachments/assets/ba995457-4cdf-4d7b-a563-759d1a06eb9a">
