### ISSUE TITLE
Support AMD

### ISSUE THREAD

**Issue by roccivic** [roccivic/cron-converter#9]
It would be nice to support AMD perhaps via a UMD gulp task for the browser build.

https://github.com/umdjs/umd
https://github.com/eduardolundgren/gulp-umd

**Comment by rstacruz** [comment]
It looks like you're using browserify. there's no need for that, just produce a standalone build.

```
browserify -s cronConverter src/cron.js | uglifyjs -cm > cron.min.js
```

**Comment by rstacruz** [comment]
oh, it looks like you already do a standalone build—in that case yes, you get amd for free!

**Comment by roccivic** [comment]
You're right, it is indeed free.
I didn't realise that browserify already wrapped the module in a UMD template.
